### PR TITLE
delete helper, add @apply

### PR DESCRIPTION
**Pull request by secretpray**
Remove tailwind helper
Remove tailwind test helper
Add apply class to application.tailwind.css

### CODE REVIEW

**Comment by msducheminjr** [comment]
Hi @secretpray !

Thank you so much for your contribution! Between this pull request and your YouTube comments, it provided a really good educational opportunity. Your contribution also brought to light that I had forgotten to style the `Resend confirmation instructions` button in the `unlocks/new.html.erb` file.

Based on your feedback on the video, I have eliminated the use of `html_safe` in the `TailwindHelper` as it is a security concern and completely unnecessary for this use case.

Ultimately I will be declining this pull request because I want the granular individual HTML classes available in the DOM so that I can manipulate them by adding and removing using Stimulus. As I'm sure you know making a `tw_success_button` class and applying a directive to it only places the `tw_success_button` class in the DOM and applies the Tailwind classes at the CSS level.

Helper page source HTML:
```html
<input type="submit" name="commit" value="Resend confirmation instructions" class="font-semibold text-gray-100 bg-blue-500 hover:bg-blue-800 px-3 py-1 mt-1 mb-2 rounded-lg" data-disable-with="Resend confirmation instructions">
```
Directive page source HTML:
```html
<input type="submit" name="commit" value="Resend confirmation instructions" class="tw_success_button" data-disable-with="Resend confirmation instructions">
```

As I'm noting in the video I'm doing on this, there may be a point in time where I would want to move portions of the repeated classes to Tailwind directives in the future. As of right now, I'm not entirely sure what I'm going to do on the Stimulus side yet, so I would consider this premature optimization in this case.

Once again, I sincerely thank you for your input, feedback, engagement, and effort to contribute. I'll refer to your pull request in both the GitHub issue and the commit where I fix the `.html_safe`. I look forward to continued interaction.

**Comment by msducheminjr** [comment]
Feedback addressed in commit 22892131f504a0ae. Closing PR. Will reference in issue.

**Comment by secretpray** [comment]
Thank you for your reply.
I am not at all insisting on including my pull request in your project. It was created solely for the convenience of viewing code edits.
Keep creating your Youtube videos, they are very useful and I enjoy watching them.

**Comment by msducheminjr** [comment]
Thanks again! I just got done recording the video where I interact with this pull request, and it was one of my favorite videos that I've ever recorded. It should be up sometime within the next week or so.

> Thank you for your reply. I am not at all insisting on including my pull request in your project. It was created solely for the convenience of viewing code edits. Keep creating your Youtube videos, they are very useful and I enjoy watching them.

**Pull request closed without merging**
